version: '3'

services:
    postgres:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data  
    web:
        build: .
        command: bash -c "bundle exec rails db:reset db:migrate db:seed && bundle exec rails server -b 0.0.0.0"
        volumes:
            - .:/rails
        depends_on:
            - postgres
            - redis
        ports:
        - '3000:3000'
        env_file:
            - ./config/application.yml
        environment:
            - DATABASE_URL=postgresql://postgres:password@postgres:5432/shopping_cart_development
            - REDIS_URL=redis://redis:6379/0
    sidekiq:
        build: .
        command: bundle exec sidekiq
        volumes:
            - .:/rails
        depends_on:
            - postgres
            - redis
        env_file:
            - ./config/application.yml
        environment:
            - DATABASE_URL=postgresql://postgres:password@postgres:5432/shopping_cart_development
            - REDIS_URL=redis://redis:6379/0
    test:
        build: .
        command: bash -c "RAILS_ENV=test bundle exec rails db:reset db:migrate db:seed && RAILS_ENV=test bundle exec rspec"
        volumes:
            - .:/rails
        depends_on:
            - postgres
            - redis
        env_file:
            - ./config/application.yml
        environment:
            - DATABASE_URL=postgresql://postgres:password@postgres:5432/shopping_cart_test
            - REDIS_URL=redis://redis:6379/0
volumes:
    postgres13:
    redis_data: